# Generated by Django 5.2 on 2025-05-05 13:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Avaliation type's name")),
            ],
            options={
                'verbose_name': 'Avaliation Type',
                'verbose_name_plural': 'Avaliations Types',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="City's name")),
                ('uf', models.CharField(max_length=2, verbose_name="City's UF")),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Course's name")),
                ('workload', models.FloatField(verbose_name="Course's workload")),
                ('month_duration', models.IntegerField(verbose_name="Course's duration in months")),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Discipline's name")),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Area's name")),
            ],
            options={
                'verbose_name': 'Knowledge area',
                'verbose_name_plural': 'Knowledge areas',
            },
        ),
        migrations.CreateModel(
            name='Ocupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Ocupation's name")),
            ],
            options={
                'verbose_name': 'Ocupation',
                'verbose_name_plural': 'Ocupations',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Shift type')),
                ('morning', models.BooleanField(verbose_name='Morning shift')),
                ('nocturnal', models.BooleanField(verbose_name='Nocturnal shift')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name="Avaliation's description")),
                ('grade', models.FloatField(verbose_name="Avaliation's grade")),
                ('type', models.CharField(max_length=99, verbose_name="Avaliation's type")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Avaliation',
                'verbose_name_plural': 'Avaliations',
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Institution's name")),
                ('website', models.CharField(max_length=99, verbose_name="Institution's website")),
                ('phone', models.CharField(max_length=13, verbose_name="Instituion's phone number")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name="Person's city")),
            ],
            options={
                'verbose_name': 'Educational Institution',
                'verbose_name_plural': 'Educational Institutions',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name="Course's institution"),
        ),
        migrations.AddField(
            model_name='discipline',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name="Course's area"),
        ),
        migrations.AddField(
            model_name='course',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name="Course's area"),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Person's name")),
                ('father_name', models.CharField(max_length=99, verbose_name="Person's father's name")),
                ('mother_name', models.CharField(max_length=99, verbose_name="Person's mother's name")),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name="Person's CPF")),
                ('birthday', models.DateField(default=datetime.date(2025, 5, 5), verbose_name="Person's birthday")),
                ('email', models.CharField(max_length=99, verbose_name="Person's email")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name="Person's city")),
                ('ocupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupation', verbose_name="Person's ocupation")),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Ocorrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Ocorrence description')),
                ('date', models.DateField(default=datetime.date(2025, 5, 5), verbose_name="Ocorrence's date")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Ocorrence',
                'verbose_name_plural': 'Ocorrences',
            },
        ),
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_number', models.IntegerField(verbose_name="Person's number of faults")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Frequence',
                'verbose_name_plural': 'Frequences',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2025, 5, 5), verbose_name="Register's start date")),
                ('end_date_prevision', models.DateField(default=datetime.date(2029, 5, 4), verbose_name="Register's end date prevision")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name='Educational institution')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name="Session's name")),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name="Session's shift")),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='DisciplinesPerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.FloatField(verbose_name="Course's workload")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name="Session's shift")),
            ],
            options={
                'verbose_name': 'Disciplines per course',
                'verbose_name_plural': 'Disciplines per courses',
            },
        ),
    ]
