# Generated by Django 5.2.1 on 2025-05-19 11:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True, verbose_name="Occupation's name")),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'occupations',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='ocupation',
        ),
        migrations.RemoveField(
            model_name='city',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='course',
            name='month_duration',
        ),
        migrations.AddField(
            model_name='avaliation',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'occupation': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name="Course's discipline"),
        ),
        migrations.AddField(
            model_name='course',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'occupation': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Avaliation's description"),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='type',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Avaliation's type"),
        ),
        migrations.AlterField(
            model_name='avaliationtype',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Avaliation type's name"),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="City's name"),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name="Course's institution"),
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledgeArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name="Course's area"),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Course's name"),
        ),
        migrations.AlterField(
            model_name='course',
            name='workload',
            field=models.FloatField(blank=True, null=True, verbose_name="Course's workload"),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='knowledgeArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name="Course's area"),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Discipline's name"),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name="Session's shift"),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='workload',
            field=models.FloatField(blank=True, null=True, verbose_name="Course's workload"),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name="Person's city"),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Institution's name"),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name="Instituion's phone number"),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='website',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Institution's website"),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='fault_number',
            field=models.IntegerField(blank=True, null=True, verbose_name="Person's number of faults"),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Area's name"),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name="Ocorrence's date"),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name="Ocorrence's description"),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Person's birthday"),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name="Person's city"),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name="Person's CPF"),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Person's email"),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Person's father's name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Person's mother's name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Person's name"),
        ),
        migrations.AlterField(
            model_name='register',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='register',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='register',
            name='end_date_prevision',
            field=models.DateField(default=datetime.datetime(2029, 5, 18, 8, 41, 43, 108683), verbose_name="Register's end date prevision"),
        ),
        migrations.AlterField(
            model_name='register',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name='Educational institution'),
        ),
        migrations.AlterField(
            model_name='register',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Register's start date"),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name="Session's name"),
        ),
        migrations.AlterField(
            model_name='session',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name="Session's shift"),
        ),
        migrations.AlterField(
            model_name='shift',
            name='morning',
            field=models.BooleanField(blank=True, null=True, verbose_name='Morning shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Shift type'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='nocturnal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nocturnal shift'),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.occupation', verbose_name="Person's occupation"),
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2, null=True, verbose_name="UF's name")),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name="City's name")),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.DeleteModel(
            name='Ocupation',
        ),
    ]
