# Generated by Django 5.0.7 on 2025-05-12 13:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='State abbreviation')),
            ],
            options={
                'verbose_name': 'State (UF)',
                'verbose_name_plural': 'States (UFs)',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliationtype',
            options={'verbose_name': 'Avaliation Type', 'verbose_name_plural': 'Avaliation Types'},
        ),
        migrations.AlterModelOptions(
            name='disciplinespercourse',
            options={'verbose_name': 'Discipline per Course', 'verbose_name_plural': 'Disciplines per Course'},
        ),
        migrations.AlterModelOptions(
            name='knowledgearea',
            options={'verbose_name': 'Knowledge Area', 'verbose_name_plural': 'Knowledge Areas'},
        ),
        migrations.AlterModelOptions(
            name='ocorrence',
            options={'verbose_name': 'Occurrence', 'verbose_name_plural': 'Occurrences'},
        ),
        migrations.AlterModelOptions(
            name='ocupation',
            options={'verbose_name': 'Occupation', 'verbose_name_plural': 'Occupations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='grade',
            field=models.FloatField(verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliationtype', verbose_name='Avaliation Type'),
        ),
        migrations.AlterField(
            model_name='avaliationtype',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=99, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name='Knowledge area'),
        ),
        migrations.AlterField(
            model_name='course',
            name='month_duration',
            field=models.IntegerField(verbose_name='Duration in months'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='workload',
            field=models.FloatField(verbose_name='Workload'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='knowledgeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.knowledgearea', verbose_name='Knowledge area'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Discipline name'),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='disciplinespercourse',
            name='workload',
            field=models.FloatField(verbose_name='Workload'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Institution name'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='website',
            field=models.CharField(max_length=99, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='frequence',
            name='fault_number',
            field=models.IntegerField(verbose_name='Number of faults'),
        ),
        migrations.AlterField(
            model_name='knowledgearea',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Knowledge area'),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ocorrence',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ocupation',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Occupation name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=99, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=99, verbose_name="Father's name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(max_length=99, verbose_name="Mother's name"),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ocupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupation', verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='register',
            name='end_date_prevision',
            field=models.DateField(default=datetime.date(2029, 5, 11), verbose_name='Estimated end date'),
        ),
        migrations.AlterField(
            model_name='register',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.educationalinstitution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='register',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Session name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=99, verbose_name='Shift name'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliation', verbose_name='Avaliation')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discipline', verbose_name='Discipline')),
                ('frequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frequence', verbose_name='Frequence')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='State (UF)'),
        ),
    ]
