# Generated by Django 5.2.1 on 2025-05-19 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_occupation_remove_person_ocupation_remove_city_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_date_prevision',
            field=models.DateField(default=datetime.datetime(2029, 5, 18, 8, 42, 1, 112650), verbose_name="Register's end date prevision"),
        ),
    ]
