# Generated by Django 5.2.1 on 2025-05-19 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_register_end_date_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_date_prevision',
            field=models.DateField(default=datetime.datetime(2029, 5, 18, 9, 38, 48, 495912), verbose_name="Register's end date prevision"),
        ),
    ]
