# Generated by Django 5.2.1 on 2025-05-19 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_register_end_date_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='end_date_prevision',
            field=models.DateField(default=datetime.datetime(2029, 5, 18, 9, 40, 54, 477148), verbose_name="Register's end date prevision"),
        ),
    ]
